name: ESLint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Install dependencies
      run: npm install --no-package-lock eslint eslint-plugin-react --legacy-peer-deps
      working-directory: src/frontend/

    - name: Run ESLint
      run: npx eslint --max-warnings $(git ls-files '*.js' '*.jsx' '*.ts' '*.tsx')
      working-directory: src/frontend/