name: ESLint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      working-directory: src/frontend
    - name: Run ESLint
      run: eslint src/ --ext .js,.jsx,.ts,.tsx
      working-directory: src/frontend