name: ESLint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

    - name: Run ESLint
      run: npx eslint src/. --ext .js,.jsx,.ts,.tsx
      working-directory: src/frontend/