name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pylint
        pip install pytest==7.1.3
        pip install flask-cors
        pip install BeautifulSoup4
        pip install Flask-Session2
        pip install authlib
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      working-directory: src/backend
